### ISSUE TITLE
Improperly rendered hearts

### ISSUE THREAD

**Issue by zackschuster** [geon/xkcd_543#1]
Some hearts are drawn like diamonds, while the top hearts are compressed to meaningless. Drawing appears to be deterministic (see screenshots), so this behavior is relevant to all users.

- [Screenshot 1](https://screenshots.firefox.com/iwKrwe1gy54k3ZBj/geon.github.io)
- [Screenshot 2](https://screenshots.firefox.com/Ei8nTJEbBpEqMpH5/geon.github.io)

**Comment by geon** [comment]
It is not a bug in the code, but the result of how the upper curve of the heart disorts the triangle above it. Not really any way around it, that I can see.
